name: Main Workflow

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger the workflow

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_SYMBOLS_ALLOWED }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Backend Docker Image
        run: docker build -t bruno74t/quirky-weather-backend:v1 ./quirky-weather-backend

      - name: Push Backend Docker Image
        run: docker push bruno74t/quirky-weather-backend:v1

  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_SYMBOLS_ALLOWED }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Frontend Docker Image
        run: docker build -t bruno74t/quirky-weather-frontend:v1 ./quirky-weather-app

      - name: Push Frontend Docker Image
        run: docker push bruno74t/quirky-weather-frontend:v1
